### ISSUE TITLE
shooting while zoomed

### ISSUE THREAD

**Issue by ste775** [relaxtakenotes/enhanced-hl2-weapons#1]
shooting while zoomed works fine at first, however once i zoom out and zoom in again every time i try and shoot the fov immediately goes back to the unzoomed state. i have tried this with and without any addons and the problem still persists. i am not using any beta branches and no lua errors appear in the console.

**Comment by relaxtakenotes** [comment]
i dont rly understand what u mean here, so can you send me a video?

**Comment by ste775** [comment]
https://github.com/relaxtakenotes/enhanced-hl2-weapons/assets/77976378/da333084-0534-4408-a7e4-4e33876ce39f

**Comment by relaxtakenotes** [comment]
cant replicate... try with a beta branch

**Comment by ste775** [comment]
issue still occurs even on the x86-x64 branch

**Comment by relaxtakenotes** [comment]
u sure u have all mods disabled?

**Comment by ste775** [comment]
yes

**Comment by relaxtakenotes** [comment]
idk what's the issue then lol

**Comment by ste775** [comment]
atleast one other person has had this issue as well so i dont think it could be down to the user

**Comment by relaxtakenotes** [comment]
try the newest update and see if it fixes it for you

**Comment by relaxtakenotes** [comment]
im gonna assume this is fixed because no one else complained and the new method wont break THAT way
