### ISSUE TITLE
'attempt to index upvalue'

### ISSUE THREAD

**Issue by Spork20** [relaxtakenotes/enhanced-hl2-weapons#5]
[Enhanced (HL2) Viewmodels] lua/autorun/client/ehw_visual.lua:145: attempt to index upvalue 'allowed' (a nil value)
    1. v - lua/autorun/client/ehw_visual.lua:145
        2. unknown - lua/includes/modules/hook.lua:96

[Enhanced (HL2) Viewmodels] lua/autorun/client/ehw_visual.lua:74: attempt to index upvalue 'allowed' (a nil value)
    1. unknown - lua/autorun/client/ehw_visual.lua:74
        2. unknown - lua/includes/modules/concommand.lua:54

Received this after crashing and forcing myself to restart my pc, tried reinstalling the addon, verifying integrity of files, deleting the config.

I found that the addon conflicts with Dlib however before the crash, both worked fine together

[DLib] 
[ERROR] lua/autorun/client/ehw_visual.lua:145: attempt to index upvalue 'allowed' (a nil value)
  1. __event - lua/autorun/client/ehw_visual.lua:145

    1. unknown - lua/dlib/modules/hook.lua:1236

**Comment by relaxtakenotes** [comment]
delete ehw_allowed.json in the data folder of your game

**Comment by Spork20** [comment]
This solved the issue, thank you! Sorry if this bug report seemed stupid I just had no idea how to fix it

**Comment by relaxtakenotes** [comment]
it's not rly stupid it's just a very weird edge case that normally shouldn't happen
